drop schema if exists trailerplan;
create schema trailerplan authorization sa;

drop table RaceEntity if exists;

create table RaceEntity (
        id              int generated by default as identity (start with 1 increment by 1) unique
    ,   race_name       VARCHAR(100) not null
    ,   challenge_name  VARCHAR(200) null
    ,   distance        FLOAT not null
    ,   race_date       varchar(10) null
    ,   elevation_up    int null
    ,   elevation_down  int null
    ,   itra_point      int not null
    ,   departure_city  VARCHAR(100) null
    ,   arrival_city    varchar(100) null
    ,   maximum_time    float null
    ,   country         varchar(100) not null
    ,   city_region     VARCHAR(100) null
    ,   url             VARCHAR (200) not null
);
